[package]
name = "wikidata-processing"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bzip2 = { version = "0.4.3"}
rayon = "1.5.1"
serde = "1.0.126"
serde_json = "1.0.64"
wikidata = "0.2.0"
